name: Deploy to EKS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  CLUSTER_NAME: Testing-My-EKS

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: docker build -t my-node-app .

      - name: Tag image
        run: docker tag my-node-app:latest 702358135571.dkr.ecr.ap-south-1.amazonaws.com/my-node-app:latest

      - name: Push image
        run: docker push 702358135571.dkr.ecr.ap-south-1.amazonaws.com/my-node-app:latest

      - name: Install kubectl
        run: |
          curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.27.0/2023-05-11/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ap-south-1 --name Testing-My-EKS

      - name: Deploy to EKS
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml